GET http://fsopart3-px7k.onrender.com/api/persons/

###

GET http://fsopart3-px7k.onrender.com/info

###

GET http://fsopart3-px7k.onrender.com/api/persons/2

###
GET http://fsopart3-px7k.onrender.com/api/persons/10

###
DELETE http://fsopart3-px7k.onrender.com/api/persons/1

###
POST http://fsopart3-px7k.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "firstname lastname",
    "number": "1111"
}

###
POST http://fsopart3-px7k.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "1111"
}

###
POST http://fsopart3-px7k.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "firstname lastname"
}

###
POST http://fsopart3-px7k.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "1111"
}



