GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons/10

###
DELETE http://localhost:3001/api/persons/65b91ddb4e4a1bcbaa94bdbc

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "firstname lastname",
    "number": "1111"
}

###
PUT http://localhost:3001/api/persons/65c3c8dfab0b7c32897137f0 HTTP/1.1
content-type: application/json

{
    "name": "firstname lastname"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "1111"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "firstname lastname"
}



###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "1111"
}



